default:
	$(MAKE) -C Main default > /dev/null
	$(MAKE) -C Character default > /dev/null
	$(MAKE) -C item default > /dev/null

clean:
	$(MAKE) -C Main clean
	$(MAKE) -C Character clean
	$(MAKE) -C item clean
